### ISSUE TITLE
Not working after rqrcode 1.0.1

### ISSUE THREAD

**Issue by 1am** [jabbrwcky/prawn-qrcode#22]
Hi.

I have a script which generates qrcodes working perfectly fine with prawn-qrcode 0.3.1
I've just cleaned my dev environment and recreated it and now it stopped working with the following:

```
	17: from src/generate-labels.rb:241:in `block in <main>'
	16: from src/generate-labels.rb:241:in `each_with_index'
	15: from /usr/local/lib/ruby/2.6.0/csv/table.rb:337:in `each'
	14: from /usr/local/lib/ruby/2.6.0/csv/table.rb:337:in `each'
	13: from src/generate-labels.rb:253:in `block (2 levels) in <main>'
	12: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/graphics/transformation.rb:82:in `translate'
	11: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/graphics/transformation.rb:155:in `transformation_matrix'
	10: from src/generate-labels.rb:254:in `block (3 levels) in <main>'
	 9: from src/generate-labels.rb:168:in `label_gen'
	 8: from src/generate-labels.rb:107:in `label_draw_qrcode'
	 7: from /usr/local/bundle/gems/prawn-qrcode-0.3.1/lib/prawn/qrcode.rb:97:in `render_qr_code'
	 6: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document/bounding_box.rb:157:in `bounding_box'
	 5: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document/bounding_box.rb:196:in `init_bounding_box'
	 4: from /usr/local/bundle/gems/prawn-qrcode-0.3.1/lib/prawn/qrcode.rb:101:in `block in render_qr_code'
	 3: from /usr/local/bundle/gems/prawn-qrcode-0.3.1/lib/prawn/qrcode.rb:101:in `each_index'
	 2: from /usr/local/bundle/gems/prawn-qrcode-0.3.1/lib/prawn/qrcode.rb:104:in `block (2 levels) in render_qr_code'
	 1: from /usr/local/bundle/gems/prawn-qrcode-0.3.1/lib/prawn/qrcode.rb:104:in `each_index'
/usr/local/bundle/gems/prawn-qrcode-0.3.1/lib/prawn/qrcode.rb:106:in `block (3 levels) in render_qr_code': undefined method `dark?' for #<RQRCode::QRCode:0x0000558dfdc40280> (NoMethodError)
```

It seems that it was broken by recent releases of 1.0.1 of https://rubygems.org/gems/rqrcode
which changed it's API while prawn-qrcode accepts it by https://github.com/jabbrwcky/prawn-qrcode/blob/master/prawn-qrcode.gemspec#L44 

Is there some way to fix it on my own without affecting the library?

**Comment by 1am** [comment]
My solution so far was the following:

In Gemfile specify exact commits or tags to use:
```
gem 'rqrcode', :git => 'https://github.com/whomwah/rqrcode.git', :tag => 'v0.10.1'
gem 'prawn-qrcode', :git => 'https://github.com/jabbrwcky/prawn-qrcode.git', :ref => '8616dda00cd1f4ef296e283e53793edb3f56bb1f'
```

In my script replace:
```
require 'prawn/qrcode`
```

With 
```
require 'bundler'
Bundler.require(:default)
```

and it works again

**Comment by jabbrwcky** [comment]
Starting with 0.4.0 prawn-qrcode breaks compatibility with rqrcode versions <1.0.0
